In [2]:
import pandas as pd
import numpy as np 
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go


In [4]:
df= pd.read_csv("df_localidad.csv",  sep=',')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 20: invalid continuation byte

In [77]:
df

Unnamed: 0  precipitacion  Campaña  mes      Cultivo  idProvincia  \
0              29           56.2  1987/88  1.0      Alpiste            6   
1              30           56.2  1987/88  1.0      Alpiste            6   
2              39           56.2  1987/88  1.0      Alpiste            6   
3              70           56.2  1987/88  1.0        Avena            6   
4             100           56.2  1987/88  1.0        Avena            6   
...           ...            ...      ...  ...          ...          ...   
16262      263796            NaN  2019/20  NaN  Trigo total            6   
16263      263800            NaN  2019/20  NaN  Trigo total            6   
16264      263801            NaN  2019/20  NaN  Trigo total            6   
16265      263825            NaN  2019/20  NaN  Trigo total            6   
16266      263830            NaN  2019/20  NaN  Trigo total            6   

       idDepartamento  Sup_Sembrada  Sup_Cosechada  Producción  Rendimiento  
0                 462            50           50.0        50.0       1000.0  
1                 469           170          160.0       190.0       1188.0  
2                 686           400          400.0       480.0       1200.0  
3                 210          2200            0.0         0.0          0.0  
4                 413          3500          300.0       600.0       2000.0  
...               ...           ...            ...         ...          ...  
16262             413         32000        32000.0    134400.0       4200.0  
16263             462         28000        27200.0    103360.0       3800.0  
16264             469         51000        49325.0    180036.0       3650.0  
16265             686         30000        29750.0    130900.0       4400.0  
16266             714         35300        33718.0    144987.0       4300.0  

[16267 rows x 11 columns]

In [78]:
#borramos los datos NaN
df.dropna(inplace=True)

In [79]:
df

Unnamed: 0  precipitacion  Campaña   mes      Cultivo  idProvincia  \
0              29           56.2  1987/88   1.0      Alpiste            6   
1              30           56.2  1987/88   1.0      Alpiste            6   
2              39           56.2  1987/88   1.0      Alpiste            6   
3              70           56.2  1987/88   1.0        Avena            6   
4             100           56.2  1987/88   1.0        Avena            6   
...           ...            ...      ...   ...          ...          ...   
15821      256913          157.0  2014/15  12.0  Trigo total            6   
15822      256916          157.0  2014/15  12.0  Trigo total            6   
15823      256917          157.0  2014/15  12.0  Trigo total            6   
15824      256941          157.0  2014/15  12.0  Trigo total            6   
15825      256946          157.0  2014/15  12.0  Trigo total            6   

       idDepartamento  Sup_Sembrada  Sup_Cosechada  Producción  Rendimiento  
0                 462            50           50.0        50.0       1000.0  
1                 469           170          160.0       190.0       1188.0  
2                 686           400          400.0       480.0       1200.0  
3                 210          2200            0.0         0.0          0.0  
4                 413          3500          300.0       600.0       2000.0  
...               ...           ...            ...         ...          ...  
15821             413         16000        16000.0     62400.0       3900.0  
15822             462         14710        14710.0     58840.0       4000.0  
15823             469         26080        26080.0    101710.0       3900.0  
15824             686         15000        15000.0     63000.0       4200.0  
15825             714          9800         9700.0     36860.0       3800.0  

[15826 rows x 11 columns]

In [80]:
del df['Unnamed: 0']

In [81]:
def Rendimiento(Rendimiento:str) -> int:
    """
    This function encodes the rendimiento variable.
    """
    
    if Rendimiento >= 2000: return 1
    else: return 0

In [82]:
df["Rendimiento"] = df["Rendimiento"].apply(Rendimiento)

In [8]:
df

precipitacion  Campaña        mes      Cultivo     Provincia  \
0                56.2  1987/88      enero          Ajo  BUENOS AIRES   
1                56.2  1987/88      enero          Ajo  BUENOS AIRES   
2                56.2  1987/88      enero          Ajo  BUENOS AIRES   
3                56.2  1987/88      enero          Ajo  BUENOS AIRES   
4                56.2  1987/88      enero          Ajo  BUENOS AIRES   
...               ...      ...        ...          ...           ...   
256958          157.0  2014/15  diciembre  Trigo total  BUENOS AIRES   
256959          157.0  2014/15  diciembre  Trigo total  BUENOS AIRES   
256960          157.0  2014/15  diciembre  Trigo total  BUENOS AIRES   
256961          157.0  2014/15  diciembre  Trigo total  BUENOS AIRES   
256962          157.0  2014/15  diciembre  Trigo total  BUENOS AIRES   

              Departamento  idProvincia  idDepartamento  Sup_Sembrada  \
0                ARRECIFES            6              77            10   
1             BAHIA BLANCA            6              56            10   
2                 BALCARCE            6              63           258   
3       GENERAL PUEYRREDON            6             357             3   
4        GENERAL RODRIGUEZ            6             364             3   
...                    ...          ...             ...           ...   
256958     TRENQUE LAUQUEN            6             826         49800   
256959        TRES ARROYOS            6             833        129000   
256960          TRES LOMAS            6             847          8100   
256961           VILLARINO            6             875         59000   
256962              ZARATE            6             882          1700   

        Sup_Cosechada Producción  Rendimiento  
0                10.0         35            1  
1                10.0         30            1  
2               258.0        910            1  
3                 3.0         10            1  
4                 3.0         10            1  
...               ...        ...          ...  
256958        49800.0     154580            1  
256959       109040.0     393612            1  
256960         8100.0      21860            1  
256961        57200.0      91696            0  
256962         1650.0       5940            1  

[256963 rows x 12 columns]

In [83]:
#cambiamos rendimiento por Target que es lo que buscamos predecir
df["target"] = df["Rendimiento"]

In [84]:
df

precipitacion  Campaña   mes      Cultivo  idProvincia  idDepartamento  \
0               56.2  1987/88   1.0      Alpiste            6             462   
1               56.2  1987/88   1.0      Alpiste            6             469   
2               56.2  1987/88   1.0      Alpiste            6             686   
3               56.2  1987/88   1.0        Avena            6             210   
4               56.2  1987/88   1.0        Avena            6             413   
...              ...      ...   ...          ...          ...             ...   
15821          157.0  2014/15  12.0  Trigo total            6             413   
15822          157.0  2014/15  12.0  Trigo total            6             462   
15823          157.0  2014/15  12.0  Trigo total            6             469   
15824          157.0  2014/15  12.0  Trigo total            6             686   
15825          157.0  2014/15  12.0  Trigo total            6             714   

       Sup_Sembrada  Sup_Cosechada  Producción  Rendimiento  target  
0                50           50.0        50.0            0       0  
1               170          160.0       190.0            0       0  
2               400          400.0       480.0            0       0  
3              2200            0.0         0.0            0       0  
4              3500          300.0       600.0            1       1  
...             ...            ...         ...          ...     ...  
15821         16000        16000.0     62400.0            1       1  
15822         14710        14710.0     58840.0            1       1  
15823         26080        26080.0    101710.0            1       1  
15824         15000        15000.0     63000.0            1       1  
15825          9800         9700.0     36860.0            1       1  

[15826 rows x 11 columns]

In [85]:
#borramos  la columna de Rendimiento que no la reemplazo "target"
del df["Rendimiento"]

In [86]:
#borramos las columnas categoricas de "campaña" y "cultivo"
del df["Campaña"]

In [87]:
del df["Cultivo"]

In [88]:
del df["mes"]

In [89]:
#Deep=true en el metodo Copy, signidica que quiero aplicar la data del DF originaly hacer cambios sin que esto afecte la data original
X = df.drop(columns=["target"]).copy(deep=True)

In [90]:
X.head()

precipitacion  idProvincia  idDepartamento  Sup_Sembrada  Sup_Cosechada  \
0           56.2            6             462            50           50.0   
1           56.2            6             469           170          160.0   
2           56.2            6             686           400          400.0   
3           56.2            6             210          2200            0.0   
4           56.2            6             413          3500          300.0   

   Producción  
0        50.0  
1       190.0  
2       480.0  
3         0.0  
4       600.0

In [91]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15826 entries, 0 to 15825
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   precipitacion   15826 non-null  float64
 1   idProvincia     15826 non-null  int64  
 2   idDepartamento  15826 non-null  int64  
 3   Sup_Sembrada    15826 non-null  int64  
 4   Sup_Cosechada   15826 non-null  float64
 5   Producción      15826 non-null  float64
dtypes: float64(3), int64(3)
memory usage: 865.5 KB


In [92]:
y= df["target"].copy(deep=True)

In [93]:
y

0        0
1        0
2        0
3        0
4        1
        ..
15821    1
15822    1
15823    1
15824    1
15825    1
Name: target, Length: 15826, dtype: int64

In [94]:
#Preparando la data para el training
from sklearn.model_selection import train_test_split

In [95]:
X_train, X_test, y_train, y_test =train_test_split(X,y, test_size=0.33, random_state=42)

In [96]:
y_train

3574     0
14900    1
4352     1
7624     1
2648     1
        ..
13418    1
5390     0
860      0
15795    1
7270     0
Name: target, Length: 10603, dtype: int64

In [97]:
#importamos algoritmos
from sklearn.neighbors import KNeighborsClassifier #KNN
from sklearn.linear_model import LogisticRegression #Regresion logistica
from sklearn.ensemble import RandomForestClassifier # Random Forest

In [98]:
knn= KNeighborsClassifier() #neighbors = 5 (default)
lgr= LogisticRegression()   #(DEFAULT)
rfc= RandomForestClassifier() # trees=100 (Default)

In [99]:
print(type(knn))
print(type(lgr))
print(type(rfc))

<class 'sklearn.neighbors._classification.KNeighborsClassifier'>
<class 'sklearn.linear_model._logistic.LogisticRegression'>
<class 'sklearn.ensemble._forest.RandomForestClassifier'>


In [100]:
#train Knn
knn.fit (X_train, y_train)

KNeighborsClassifier()

In [101]:
#Predict whit KNN
knn.predict(X_test)

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [102]:
y_test

8273     1
169      1
14862    1
8845     1
4098     0
        ..
7556     1
549      1
12299    1
13202    1
13449    1
Name: target, Length: 5223, dtype: int64

In [103]:
#train logistic Regretion
lgr.fit(X_train, y_train)

LogisticRegression()

In [104]:
#predict whit logistic Reg
lgr.predict(X_test)

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [105]:
#train random forest
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [106]:
#Predict whit random forest
rfc.predict(X_test)

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)